model: 'GCNGraphReg'
num_layers: 4
hidden_dim: 145
residual: True
batch_norm: True
readout: 'mean'
batch_size: 128
epochs: 140
init_lr: .001
lr_factor: 0.5
lr_patience: 10
min_lr: .00001
use_counts: True
count_type: 'resdist'
count_files: ['zinc_resdist.json']
idx_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
description: 'GCN-100k resistance distance'
