model: 'GCNCutPred'
num_layers: 4
hidden_dim: 145
residual: True
batch_norm: True
readout: 'mean'
batch_size: 128
epochs: 60
init_lr: .001
lr_factor: 0.5
lr_patience: 10
min_lr: .00001
use_counts: False
count_type: 'resdist'
count_files: ['biconn_resdist.json']
idx_list: [0, 1, 2, 3, 4, 5]
description: 'GCN-100k resistance distance'
mode: 'node'
