model: 'GINCutPred'
num_layers: 4
hidden_dim: 110
residual: True
batch_norm: True
readout: 'sum'
batch_size: 128
epochs: 60
init_lr: .001
lr_factor: 0.5
lr_patience: 10
min_lr: .00001
use_counts: False
count_type: 'resdist'
count_files: ['biconn_resdist.json']
idx_list: [0, 1, 2, 3, 4, 5, 6, 7]
description: 'GIN-100k resistance distance'
mode: 'node'